apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdriven-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdriven-server
  template:
    metadata:
      labels:
        app: mdriven-server
    spec:
      containers:
        - name: mdriven-server
          image: "mdriven/mdriven-server/local:alpine"
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: mdriven-server
spec:
  type: NodePort
  selector:
    app: mdriven-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001